# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy dependency definitions
COPY package*.json ./
COPY tsconfig.json ./
COPY smithery.yaml ./

# Install dependencies without running scripts (we build explicitly later)
RUN npm install --ignore-scripts

# Copy all source files into the container
COPY . .

# Build the project
RUN npm run build

# Expose any necessary ports (if needed) 

# Start the MCP server using the built entrypoint
CMD [ "node", "build/index.js" ]
